# Generated by Django 4.0 on 2022-05-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0002_enroll_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('class_id', models.IntegerField()),
                ('action', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
