# Generated by Django 4.0 on 2022-05-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0003_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('class_id', models.IntegerField()),
                ('teacher', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
