# Generated by Django 4.0 on 2022-05-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0004_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
