# Generated by Django 4.0 on 2022-05-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0006_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=255)),
                ('book_name', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='books/')),
            ],
        ),
    ]
