# Generated by Django 4.0 on 2022-05-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0007_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='status',
            field=models.CharField(default='activated', max_length=255),
        ),
    ]
