# Generated by Django 4.0 on 2022-05-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0008_library_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='publisher_name',
            field=models.IntegerField(),
        ),
    ]
