# Generated by Django 4.0 on 2022-05-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0009_alter_library_publisher_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=255)),
                ('exam_time', models.IntegerField()),
                ('teahcer_id', models.IntegerField()),
                ('status', models.CharField(default='activated', max_length=255)),
            ],
        ),
    ]
