# Generated by Django 4.0 on 2022-05-24 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0010_quiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='teahcer_id',
            new_name='teacher_id',
        ),
    ]
