# Generated by Django 4.0 on 2022-05-25 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0012_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='question_no',
        ),
    ]
