# Generated by Django 4.0 on 2022-05-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0014_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('attempted', models.CharField(default='false', max_length=255)),
            ],
        ),
    ]
