# Generated by Django 4.0 on 2022-05-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0017_remove_results_class_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messenger', models.IntegerField()),
                ('recipient', models.IntegerField()),
                ('msg', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('status', models.CharField(default='activated', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='attempt',
            name='attempted',
            field=models.CharField(default='true', max_length=255),
        ),
    ]
